module.exports = {
  "root": true,

  "env": {
    "browser": true,
    "es6": true,
    "jest": true,
    "node": true,
  },

  "plugins": [
    "react"
  ],

  "parser": "babel-eslint",

  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true,
      "modules": true,
    },
  },

  "rules": {
    "block-scoped-var": "error",
    "brace-style": "off",
    "camelcase": "off",
    "comma-dangle": "off",
    "comma-spacing": "error",
    "comma-style": "error",
    "complexity": "off",
    "consistent-return": "error",
    "consistent-this": "off",
    "curly": "error",
    "default-case": "error",
    "dot-notation": "error",
    "eol-last": "error",
    "eqeqeq": "error",
    "func-names": "off",
    "func-style": "off",
    "guard-for-in": "error",
    "indent": ["error", "error", { "SwitchCase": 1 }],
    "key-spacing": "off",
    "max-depth": "off",
    "max-len": ["error", 120],
    "max-nested-callbacks": "off",
    "max-params": "off",
    "max-statements": "off",
    "new-cap": "error",
    "new-parens": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-catch-shadow": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-div-regex": "error",
    "no-dupe-keys": "error",
    "no-else-return": "off",
    "no-empty-character-class": "error",
    "no-empty-label": "error",
    "no-empty": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-parens": "off",
    "no-extra-semi": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-func-assign": "error",
    "no-implied-eval": "error",
    "no-inline-comments": "off",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-spaces": "off",
    "no-multi-str": "off",
    "no-multiple-empty-lines": "error",
    "no-native-reassign": "error",
    "no-negated-in-lhs": "error",
    "no-nested-ternary": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-wrappers": "error",
    "no-new": "error",
    "no-obj-calls": "error",
    "no-octal-escape": "error",
    "no-octal": "error",
    "no-plusplus": "off"
    "no-process-env": "off",
    "no-proto": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-reserved-keys": "off",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow-restricted-names": "error",
    "no-shadow": "error",
    "no-spaced-func": "error",
    "no-sparse-arrays": "error",
    "no-ternary": "off",
    "no-trailing-spaces": "error",
    "no-undef-init": "error",
    "no-undef": "error",
    "no-undefined": "error",
    "no-underscore-dangle": "off",
    "no-unreachable": "error",
    "no-unused-expressions": "error",
    "no-unused-vars": "error",
    "no-use-before-define": "error",
    "no-void": "off",
    "no-warning-comments": "off",
    "no-with": "error",
    "one-var": "off",
    "operator-assignment": ["error", "always"],
    "padded-blocks": "off",
    "quote-props": ["error", "as-needed"],
    "quotes": ["error", "single"],
    "radix": "error",
    "semi-spacing": ["error", { "before": false, "after": true }],
    "semi": ["error", "always"],
    "sort-vars": ["error", { "ignoreCase": true }],
    "space-after-keywords": "error",
    "space-before-blocks": "error",
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-return-throw-case": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "strict": ["error", "global"],
    "use-isnan": "error",
    "valid-jsdoc": "off",
    "valid-typeof": "error",
    "vars-on-top": "off",
    "wrap-iife": "error",
    "wrap-regex": "off",
    "yoda": "error",
  }
};
